global:
  scrape_interval: 10s  
  evaluation_interval: 10s  

scrape_configs:
 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] 

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']  


  - job_name: 'server'
    static_configs:
      - targets: ['quick-start-server-1:3001']  

rule_files:
  - '/etc/prometheus/rules.yml'  
