services:
  client:
    image: ghcr.io/frenzywall/collab-editor/editor:client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_URL=http://localhost:3001
      - TZ=Asia/Kolkata
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network
    

  server:
    image: ghcr.io/frenzywall/collab-editor/editor:server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TZ=Asia/Kolkata
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - app-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - WATCHTOWER_CLEANUP=true                
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_DEBUG=true  
      - TZ=Asia/Kolkata      

networks:
  app-network:
    driver: bridge