name: Cleanup Old Docker Images

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: List and delete Docker images older than a week
        run: |
          # Fetch the list of image digests older than a week
          images=$(curl -s -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
            "https://ghcr.io/v2/${{ github.repository }}/manifests" \
            | jq -r '.manifests[] | select(.created < (now - 604800)) | .digest')

          # Check if there are any images older than a week
          if [ ! -z "$images" ]; then
            echo "Cleaning up old images: $images"
            # Delete images from GHCR
            for image in $images; do
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
                "https://ghcr.io/v2/${{ github.repository }}/manifests/$image"
            done
          else
            echo "No old images found"
          fi
