name: Clean Old Docker Images

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Delete Docker images older than 3 days
        run: |
          CURRENT_DATE=$(date +%s)
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" | grep "${{ github.repository }}")

          for IMAGE in $IMAGES; do
            IMAGE_NAME=$(echo $IMAGE | awk '{print $1}')
            IMAGE_DATE=$(echo $IMAGE | awk '{print $2, $3, $4}')
            IMAGE_TIMESTAMP=$(date -d "$IMAGE_DATE" +%s)

            if [ $((CURRENT_DATE - IMAGE_TIMESTAMP)) -gt 259200 ]; then
              echo "Deleting image ${IMAGE_NAME}"
              docker rmi "$IMAGE_NAME"
            fi
          done
