name: Build and Push Docker Images

on:
  push:
    branches:
      - Production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push client Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/editor:client ./client
          docker push ghcr.io/${{ github.repository }}/editor:client

      - name: Build and push server Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/editor:server ./server
          docker push ghcr.io/${{ github.repository }}/editor:server
